### ISSUE TITLE
Failed CronJob runs get re-raised until cleaned up (and don't have message)

### ISSUE THREAD

**Issue by daaain** [wichert/k8s-sentry#13]
I found an odd issue, it seems that if there's a Failed run of a CronJob, `k8s-sentry` will keep on re-raising it as a Sentry issue approximately 8 times an hour until it's removed.

The only workaround is to delete these manually:

```sh
kubectl delete pods --field-selector status.phase=Failed --all-namespaces
```

It also seems that the error message / reason is missing, the actualy issue was container exiting with exit code 1.

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/69962/96278988-11b9c900-0fce-11eb-9bcc-1b98b0aa0915.png">

**Comment by williscool** [comment]
Having this issue also with a regualr job... complete blew out my dev sentry quote o.o

![image](https://user-images.githubusercontent.com/394931/96351304-76d1f500-1088-11eb-94ab-8cf1a8b0307c.png)

**Comment by wichert** [comment]
That definitely sounds like a real bug. I'll try to reproduce this.

**Comment by wichert** [comment]
@daaain Isn't the behaviour correct for you? I would expect a Sentry event every time the created Pod failed. For example with this Job:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: failure
spec:
  template:
    spec:
      containers:
      - name: failure
        image: busybox
        command: ["sh",  "-c", "echo Failing now ; /bin/false"]
      restartPolicy: Never
  backoffLimit: 4
```

Kubernetes will try to create and run a pod four times, resulting in four failure events. It sounds like your CronJob is setup to do 8 attempts per hour?

**Comment by wichert** [comment]
@williscool Can you show me what your Job resource looks like? In my test k8s-sentry does not report more errors than the number of times Kubernetes tries to run the job, so I'm wondering how you get 1500 events for a single Job.

**Comment by daaain** [comment]
@wichert it's a single run of the CronJob which was repeated in Sentry, the runs afterwards were successful.

It's running in a cluster with 1.16.13-gke.401

This is the template from GKE with some irrelevant bits removed:

```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: etl-sync-worker-bike-public-module-state
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        app: etl-sync-worker-bike-public-module-state
    spec:
      backoffLimit: 1
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command: ...
            image: ...
            name: etl-sync-worker-bike-public-module-state
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
  schedule: 0/2 * * * *
  startingDeadlineSeconds: 60
  successfulJobsHistoryLimit: 3
```
