### ISSUE TITLE
Bind logger

### ISSUE THREAD

**Issue by dcramer** [wichert/k8s-sentry#6]
This is more of an open conversation if its agreeable, but you have two options for monitoring k8s:

- use an existing project (e.g. i have one single project for a service)
- use a new project just for k8s

Neither quite fit how we describe Sentry with one project per service.

Anyways, I think it could be valuable for us to bind the 'logger' attribute as 'kubernetes' so if you do choose to use one project, you can then easily filter down to kubernetes-only events.

**Comment by dcramer** [comment]
Another option here would be to overload the 'platform' payload, as I believe that gets indexed as well. Right now it shows Go, which is true, but we dont really care about the Go runtime in this case, we care about it being kubernetes.

**Comment by wichert** [comment]
Can the platform payload be set? From what I remember from either the JavaScript or Python libraries the library always forces it to the implementation language.

One thing that might be interesting is to use annotations to configure the DSN. For example:

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myservice
  labels:
    app.kubernetes.io/name: myservice
  annotations:
    sentry/dsn: "https://1111111111@sentry.io/1927471"
```
